# Generated by Django 3.2.6 on 2021-08-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad_de_preguntas', models.IntegerField()),
                ('puntaje_minimo_para_aprobar', models.IntegerField()),
                ('dificultad', models.CharField(choices=[('Fácil', 'Fácil'), ('Medio', 'Medio'), ('Dicífil', 'Difícil'), ('Chaqueñaso', 'Chaqueñaso')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Niveles',
            },
        ),
    ]
